name: techable
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #riverpod
  flutter_riverpod: ^2.5.1
  image_picker: ^1.0.7
  camera: ^0.11.0
  google_mlkit_image_labeling: ^0.12.0
  google_mlkit_barcode_scanning: ^0.12.0
  qr_mobile_vision: ^5.0.0
  #text
  # flutter_tesseract_ocr: ^0.4.24
  path_provider: ^2.1.1
  path: ^1.8.3
  google_mlkit_text_recognition: ^0.13.0
  #document
  google_mlkit_document_scanner: ^0.2.0
  #cut image
  image_cropper: ^6.0.0
  #view
  flashy_tab_bar2: ^0.0.10
  #store
  shared_preferences: ^2.2.3
  #qr
  mobile_scanner: ^5.1.1
  #toast
  fluttertoast: ^8.2.5
  #lottie
  lottie: ^3.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/masterdata.txt
    - assets/splash/
    - assets/logo/
